--------------------------------------------------------
--  DDL for Table SMART_PARKING
--------------------------------------------------------

  CREATE TABLE "SMARTPARKING"."SMART_PARKING" 
   (	"ROW_ID" NUMBER, 
	"CARPARK_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE_TIME" TIMESTAMP (6), 
	"TOTAL_SLOTS" NUMBER, 
	"AVAILABLE_SLOTS" NUMBER, 
	"CARPARK_STATUS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE_TIME" TIMESTAMP (6), 
	"CARPARK_IMAGE" BLOB, 
	"PRECISE_COUNTER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("CARPARK_IMAGE") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
