--------------------------------------------------------
--  DDL for Table SMART_PARKING_IS_READY
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."SMART_PARKING_IS_READY" 
   (	"IS_SMART_PARKING_READY" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SMART_PARKING_IS_READY
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."SMART_PARKING_IS_READY" MODIFY ("IS_SMART_PARKING_READY" NOT NULL ENABLE);
